language: cpp
compiler:
  - clang++
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.5
      - ubuntu-toolchain-r-test
    packages:
      - libyajl-dev
      - libxml2-dev
      - clang-3.5
sudo: false
script: 
  - $CXX --version
  - echo $CXXFLAGS
  - clang --version
  - cd src
  - make
  - ./minmod_component
